### ISSUE TITLE
[Enhancement]: Adding different categories in Word Guessing Game

### ISSUE THREAD

**Issue by dishamodi0910** [kunjgit/GameZone#2538] opened 2023-07-20 14:33 UTC
### Is your enhancement request related to a problem? Please describe.➕

Game enhancement

Currently all categories are combined together in Word Guessing Game, so improving it will allow people to answer the questions that they are interested in.

### Describe the solution you'd like

Solution steps

Adding different categories for Word Guessing Game.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment] 2023-08-31 06:39
Hey @sasank-paria ! , This issue is already assigned to @dishamodi0910. 💗 
 You can work on other issues 🚀 
 If there is anything wrong you can contact us on [Discord🕹️](https://discord.gg/fgwk4XZfxG)👀

**Comment by kunjgit** [comment] 2023-09-25 10:19
Hey @dishamodi0910 👋!
 
 @kunjgit here, 
 Hope you are doing extremely well 😇 
 It's confirmed 🥳, GameZone is taking part in hacktoberfest and ready to have another 💥 
 Ready to have some amazing contributions once again also thank you for you support in GSSoC23 you have took us on top 5 ❤️‍🔥 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2023-10-03 06:45
Hey @dishamodi0910 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2024-01-21 05:55
Hello @dishamodi0910, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment] 2024-01-21 05:55
Hey @dishamodi0910 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Closed by kunjgit** 2024-01-21 05:55 UTC
Labels: gssoc23, level2
