### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by tejaschaudhari131** [kunjgit/GameZone#2884] opened 2023-08-15 14:17 UTC
### Is your enhancement request related to a problem? Please describe.➕

game enhancement

### Describe the solution you'd like

Check and Checkmate Detection: Implement logic to detect when a king is in check or checkmate. This would involve checking if the king is under attack and if there are no legal moves that would remove the check.

Castling: Add support for castling, a special chess move involving the king and a rook. This move can be a bit complex to implement due to the specific rules surrounding it.

En Passant: Implement the en passant rule, which allows a pawn to capture an opponent's pawn if it advances two squares from its starting position and lands beside an opposing pawn.

Promotion: Handle pawn promotion, where a pawn reaches the opposite end of the board and can be promoted to a more powerful piece (queen, rook, bishop, or knight).

Undo Move: Implement an undo move functionality that allows players to revert their moves one step at a time. This can be particularly useful for debugging and analyzing strategies

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment] 2023-08-15 14:18
Hey @tejaschaudhari131 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment] 2023-09-25 10:19
Hey @tejaschaudhari131 👋!
 
 @kunjgit here, 
 Hope you are doing extremely well 😇 
 It's confirmed 🥳, GameZone is taking part in hacktoberfest and ready to have another 💥 
 Ready to have some amazing contributions once again also thank you for you support in GSSoC23 you have took us on top 5 ❤️‍🔥 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2023-10-03 06:45
Hey @tejaschaudhari131 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2024-05-10 04:23
Hello @tejaschaudhari131, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment] 2024-05-10 04:23
Hey @tejaschaudhari131 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Closed by kunjgit** 2024-05-10 04:23 UTC
Labels: level2
