### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by Tharun-nennavath** [kunjgit/GameZone#2303] opened 2023-07-05 22:34 UTC
### Is your enhancement request related to a problem? Please describe.➕

{Game enhancement } website is not responsive. When we are scrolling the web page the entire page is moving .  This lack of responsiveness makes it difficult for users to view and navigate the website effectively on devices such as smartphones, tablets, or different-sized computer screens.

### Describe the solution you'd like

Solution steps: in CSS if  we are changing  the style position then we can resolve it.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment] 2023-07-05 22:34
Hey @Tharun-nennavath ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by Tharun-nennavath** [comment] 2023-07-05 22:41
Assign this issue to me.

**Comment by kunjgit** [comment] 2023-07-05 22:42
Hey @Tharun-nennavath ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by Tharun-nennavath** [comment] 2023-07-05 22:44
Is this issue is assigned to me.

**Comment by Tharun-nennavath** [comment] 2023-07-05 22:46
> Hey @Tharun-nennavath ! Thank you for raising an issue 💗 You can self assign the issue by commenting /assign in comment 😀 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone) Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

/assign

**Comment by Tharun-nennavath** [comment] 2023-07-21 17:12
I want to pr this issue again can i do it.

**Comment by kunjgit** [comment] 2023-09-25 10:19
Hey @Tharun-nennavath 👋!
 
 @kunjgit here, 
 Hope you are doing extremely well 😇 
 It's confirmed 🥳, GameZone is taking part in hacktoberfest and ready to have another 💥 
 Ready to have some amazing contributions once again also thank you for you support in GSSoC23 you have took us on top 5 ❤️‍🔥 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2023-10-03 06:45
Hey @Tharun-nennavath 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2024-01-21 05:54
Hello @Tharun-nennavath, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment] 2024-01-21 05:55
Hey @Tharun-nennavath ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Closed by kunjgit** 2024-01-21 05:54 UTC
Labels: gssoc23, level2
