### ISSUE TITLE
[New game]: Pokemon Generator

### ISSUE THREAD

**Issue by killerraj369** [kunjgit/GameZone#2872] opened 2023-08-10 06:12 UTC
### 🎮 Game Request

Game logic and basic description
We are all die-hard fans of Pokémon and its world. This game enables you to encounter both the familiar Pokémon you know and the ones you have yet to discover.
Click the button to meet your new Pokémon companion that's waiting for you !!!

### Point down the features

Game points
![image](https://github.com/kunjgit/GameZone/assets/87773889/29603dd2-aeb5-41d5-a044-0dbd7d79693d)
![image](https://github.com/kunjgit/GameZone/assets/87773889/230cd093-9d1c-44f8-af0d-306bbccb743e)
![image](https://github.com/kunjgit/GameZone/assets/87773889/46dbd11d-152e-4a8c-8c68-25959d671a20)
![image](https://github.com/kunjgit/GameZone/assets/87773889/89fe049d-19ee-4752-b384-901b5557a09f)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment] 2023-08-10 06:13
Hey @killerraj369 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment] 2023-09-25 10:19
Hey @killerraj369 👋!
 
 @kunjgit here, 
 Hope you are doing extremely well 😇 
 It's confirmed 🥳, GameZone is taking part in hacktoberfest and ready to have another 💥 
 Ready to have some amazing contributions once again also thank you for you support in GSSoC23 you have took us on top 5 ❤️‍🔥 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2023-10-03 06:45
Hey @killerraj369 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2024-05-10 04:23
Hello @killerraj369, Time's up!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment] 2024-05-10 04:23
Hey @killerraj369 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Closed by kunjgit** 2024-05-10 04:22 UTC
Labels: gssoc23, New Game 🎮
