### ISSUE TITLE
[New game]: Flappy Bird

### ISSUE THREAD

**Issue by BhartiNagpure** [kunjgit/GameZone#2453] opened 2023-07-16 07:49 UTC
### 🎮 Game Request

Game logic and basic description

Flappy  bird game is just for fun !

This game has two bird img which toggle after every arrowup key and looks like it fly.
and poles which continuously move in random shape .
You need to handle bird action by pressing arrowup key and pass the bird from poles.

### Point down the features

Game points

1.   Press Enter
2.  Start pressing arrowup key to control bird action.
3.  Pass the bird from random height poles .
4. Your score is based on poles you pass.

![Screenshot 2023-07-08 222619](https://github.com/kunjgit/GameZone/assets/104631882/3b6fb1a7-ee4d-4cb9-a091-d32d37df37f6)

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment] 2023-07-16 07:50
Hey @BhartiNagpure ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by BhartiNagpure** [comment] 2023-07-16 07:55
Assign me this issue.

**Comment by kunjgit** [comment] 2023-09-25 10:19
Hey @BhartiNagpure 👋!
 
 @kunjgit here, 
 Hope you are doing extremely well 😇 
 It's confirmed 🥳, GameZone is taking part in hacktoberfest and ready to have another 💥 
 Ready to have some amazing contributions once again also thank you for you support in GSSoC23 you have took us on top 5 ❤️‍🔥 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2023-10-03 06:45
Hey @BhartiNagpure 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2024-01-21 05:55
Hello @BhartiNagpure, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment] 2024-01-21 05:55
Hey @BhartiNagpure ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Closed by kunjgit** 2024-01-21 05:55 UTC
Labels: gssoc23, New Game 🎮, level3
