### ISSUE TITLE
[New game]: Simon Says game

### ISSUE THREAD

**Issue by MohanaSrinivas** [kunjgit/GameZone#2608] opened 2023-07-26 13:23 UTC
### 🎮 Game Request

In this game, the computer will show a sequence of colors one by one, and the player needs to repeat the sequence correctly by clicking on the colors. If the player makes a mistake, the game ends, and the player's final level (number of correct sequences) will be displayed.

### Point down the features

Correct Sequence: When the player correctly repeats the entire sequence shown by the computer, they earn points. You can assign a fixed number of points for each correct sequence completed. For example, you can give 10 points for each correct sequence.

Speed Bonus: To encourage faster responses, you can provide a speed bonus. If the player repeats the sequence within a certain time limit (e.g., 5 seconds), they can earn additional points. The faster they respond, the higher the speed bonus.

Level Bonus: As the game progresses, it becomes more challenging with longer sequences. You can reward the player with bonus points for reaching higher levels. For example, for every level completed, the player can get 5 bonus points.

Perfect Round Bonus: If the player completes a level without making any mistakes, they can earn extra points as a perfect round bonus.

Penalty for Mistakes: On the other hand, you can deduct points for every mistake the player makes. For example, deducting 5 points for each incorrect color clicked.

Total Score: Add up all the points earned throughout the game to calculate the player's total score. Display the score at the end of the game.

### Select program in which you are contributing

GSSoC23

Hactober

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment] 2023-07-26 13:24
Hey @MohanaSrinivas ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by misterraina** [comment] 2023-07-28 03:17
/assign
i am new to open source Contribution, I found this project interesting and i want to contribute and i can make this by whole myself now here is my question what does i have to do? do i have to make the whole project or solve by myself?

**Comment by kunjgit** [comment] 2023-09-25 10:19
Hey @MohanaSrinivas 👋!
 
 @kunjgit here, 
 Hope you are doing extremely well 😇 
 It's confirmed 🥳, GameZone is taking part in hacktoberfest and ready to have another 💥 
 Ready to have some amazing contributions once again also thank you for you support in GSSoC23 you have took us on top 5 ❤️‍🔥 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2023-10-03 06:45
Hey @MohanaSrinivas 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by MohanaSrinivas** [comment] 2023-10-15 20:34
I want to add a new game

**Comment by kunjgit** [comment] 2024-01-21 05:55
Hello @MohanaSrinivas, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment] 2024-01-21 05:55
Hey @MohanaSrinivas ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Closed by kunjgit** 2024-01-21 05:55 UTC
Labels: gssoc23, New Game 🎮
