### ISSUE TITLE
[New game]:Highway race

### ISSUE THREAD

**Issue by shishiro26** [kunjgit/GameZone#2498] opened 2023-07-19 11:30 UTC
### 🎮 Game Request

Game logic and basic description
Get ready for an adrenaline-pumping experience in "Highway Rush," an exhilarating highway race game that will test your driving skills and reflexes to the limit! Strap in and hit the accelerator as you blaze through a never-ending stretch of the highway, overtaking vehicles and scoring points with each daring pass

### Point down the features

Game pointsUse the arrow keysto steer your car left and right.
Avoid crashing into other vehicles, as colliding will end the game.
Score points by overtaking vehicles at high speeds and getting close to them without causing an accident.
Collect power-ups to enhance your speed and increase your chances of scoring higher.
Challenge your reflexes and become the fastest racer on the highway! Are you ready to push the pedal to the metal and take on the ultimate highway race? Play "Highway Rush" now and let the thrill of high-speed chases begin

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment] 2023-07-19 11:31
Hey @shishiro26 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment] 2023-09-25 10:19
Hey @shishiro26 👋!
 
 @kunjgit here, 
 Hope you are doing extremely well 😇 
 It's confirmed 🥳, GameZone is taking part in hacktoberfest and ready to have another 💥 
 Ready to have some amazing contributions once again also thank you for you support in GSSoC23 you have took us on top 5 ❤️‍🔥 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2023-10-03 06:45
Hey @shishiro26 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2024-01-21 05:55
Hello @shishiro26, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment] 2024-01-21 05:55
Hey @shishiro26 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Closed by kunjgit** 2024-01-21 05:55 UTC
Labels: gssoc23, New Game 🎮, level3
