### ISSUE TITLE
[New game]: Drum Kit

### ISSUE THREAD

**Issue by rajatnai49** [kunjgit/GameZone#3] opened 2023-05-11 17:28 UTC
### 🎮 Game Request

A drum kit is a musical instrument consisting of a set of drums and cymbals that are played by striking them with drumsticks or other percussion tools. In a virtual drum kit game, the player uses a controller, such as a keyboard or drum pad, to simulate playing a real drum kit.

The game logic of a drum kit typically involves mapping each drum or cymbal to a specific key or button on the controller. When the player strikes a drum or cymbal on the controller, the corresponding sound is played through the game's audio system. The player can then use a combination of these buttons to create a variety of rhythms and beats.

### Point down the features

- Realistic sounds: The game uses high-quality audio samples to replicate the sounds of a real drum kit, providing a realistic playing experience.
- Multiple drum kits: The game may include multiple drum kits with different sounds and styles, allowing players to experiment with different musical genres.
- Customization options: The game may allow players to customize their drum kit setup, choosing which drums and cymbals they want to use and how they are mapped to the controller.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment] 2023-05-14 03:50
you can start working on it @rajatnai49 🙂

**Comment by ZapeeoSheikh** [comment] 2023-05-19 16:19
Can i contribute through this project ? Coming from GSSOC. Please tell me more about the issue because in the issue description, the problem is not cleared.

**Comment by 584aditya** [comment] 2023-05-20 02:41
This seems little normal to me . I have worked on various Music Production Softwares. I have a better understand of music, what is perfect to where. Please Assign this issue to me. I will try my best and try to work on it.

**Comment by kunjgit** [comment] 2023-06-09 11:17
Hello @rajatnai49, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment] 2023-06-09 11:17
Hey @rajatnai49 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Closed by kunjgit** 2023-06-09 11:17 UTC
Labels: gssoc23
