### ISSUE TITLE
[New game]: GO

### ISSUE THREAD

**Issue by pxiy-a** [kunjgit/GameZone#2729] opened 2023-08-02 17:47 UTC
### 🎮 Game Request

Go is an ancient two-player strategy board game . Players take turns placing black and white stones on a 19x19 grid board, aiming to control more territory. The objective is to surround and capture opponent stones while simultaneously creating and defending one's own territories. The game is easy to learn, yet possesses immense depth and complexity, making it a favourite among enthusiasts and master players worldwide.

### Point down the features

The game has straightforward rules, yet it offers deep and intricate strategic possibilities.Players aim to control more territory by surrounding and capturing their opponent's stones.Unlike many other board games, Go doesn't eliminate players; instead, they compete until the board is full or both players agree to end the game.Go's enduring popularity is attributed to its elegant design, intellectual challenge, and its ability to captivate players of all ages and skill levels.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment] 2023-09-25 10:19
Hey @pxiy-a 👋!
 
 @kunjgit here, 
 Hope you are doing extremely well 😇 
 It's confirmed 🥳, GameZone is taking part in hacktoberfest and ready to have another 💥 
 Ready to have some amazing contributions once again also thank you for you support in GSSoC23 you have took us on top 5 ❤️‍🔥 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2023-10-03 06:45
Hey @pxiy-a 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2024-01-21 05:55
Hello @pxiy-a, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Closed by kunjgit** 2024-01-21 05:55 UTC
Labels: gssoc23, New Game 🎮

**Comment by kunjgit** [comment] 2024-01-21 05:56
Hey @pxiy-a ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
