### ISSUE TITLE
[New game]: Tic-Tac-Toe

### ISSUE THREAD

**Issue by ayon037** [kunjgit/GameZone#2333] opened 2023-07-08 06:37 UTC
### 🎮 Game Request

Tic Tac Toe is traditionally played on a 3 × 3 grid. Players take turns placing a mark in one of the cells of the grid. The goal of the game is for players to position their marks so that they make a continuous line of three cells vertically, horizontally, or diagonally.

### Point down the features

The game is played on a grid that's 3 squares by 3 squares. You are X , your friend (or the computer in this case) is O . Players take turns putting their marks in empty squares. The first player to get 3 of her marks in a row (up, down, across, or diagonally) is the winner.

### Select program in which you are contributing

I'll be using Javascript to make this game.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment] 2023-07-08 06:37
Hey @ayon037 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by ayon037** [comment] 2023-07-08 06:39
Please assign this task to me. I'm a GSSOC'23 contributor.

**Comment by kunjgit** [comment] 2023-09-25 10:19
Hey @ayon037 👋!
 
 @kunjgit here, 
 Hope you are doing extremely well 😇 
 It's confirmed 🥳, GameZone is taking part in hacktoberfest and ready to have another 💥 
 Ready to have some amazing contributions once again also thank you for you support in GSSoC23 you have took us on top 5 ❤️‍🔥 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2023-10-03 06:45
Hey @ayon037 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2024-01-21 05:55
Hello @ayon037, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment] 2024-01-21 05:55
Hey @ayon037 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Closed by kunjgit** 2024-01-21 05:54 UTC
Labels: New Game 🎮, level3
