### ISSUE TITLE
[New game]: Sokoban

### ISSUE THREAD

**Issue by U-DAY-333** [kunjgit/GameZone#2298] opened 2023-07-05 18:11 UTC
### 🎮 Game Request

Sokoban is a puzzle game where the player controls a character who must push crates or boxes onto designated storage locations in a warehouse or maze-like environment. The player can move in all four cardinal directions but can only push one box at a time. The crates cannot be pulled, and they can only be pushed from the sides, not diagonally.

The objective of Sokoban is to move all the crates to their respective storage locations. The game becomes increasingly challenging as the warehouse becomes more complex, with obstacles such as walls or immovable blocks that restrict the player's movement. The player must plan their moves carefully to avoid getting stuck or blocking any essential paths.

### Point down the features

As you progress through the levels, the complexity of the warehouse layout increases. Walls and other obstacles may block your path, making it harder to navigate and push the crates. You must carefully plan your moves to avoid getting trapped or pushing crates into inaccessible areas.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) of this project.

**Comment by kunjgit** [comment] 2023-07-05 18:12
Hey @U-DAY-333 ! 
 Thank you for raising an issue 💗 
 You can self assign the issue by commenting /assign in comment 😀 
 Make sure you follow [CODE OF CONDUCT](https://github.com/kunjgit/GameZone/blob/main/.github/CODE_OF_CONDUCT.md) and [CONTRIBUTING GUIDELINES](https://github.com/kunjgit/GameZone/blob/main/.github/CONTRIBUTING_GUIDELINE.md) 🚀 
 Don’t Forget to ⭐ our [GameZone🎮](https://github.com/kunjgit/GameZone)
 Make sure you join our [Discord🕹️](https://discord.gg/fgwk4XZfxG)

**Comment by kunjgit** [comment] 2023-09-25 10:19
Hey @U-DAY-333 👋!
 
 @kunjgit here, 
 Hope you are doing extremely well 😇 
 It's confirmed 🥳, GameZone is taking part in hacktoberfest and ready to have another 💥 
 Ready to have some amazing contributions once again also thank you for you support in GSSoC23 you have took us on top 5 ❤️‍🔥 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2023-10-03 06:45
Hey @U-DAY-333 👋!
 
 @kunjgit here, 
 Hope you are enjoying this hacktober 😀 
 We are excited to share that we are opening issue from our side where you will be going to add games on our website 🚀 
 Work on this [issue](https://github.com/kunjgit/GameZone/issues/2944) 🔥 
 and help us building GameZone 💗 
 if you still haven't joined us join us on ⁠[Discord](https://discord.gg/fgwk4XZfxG) 
 See you soon 😊

**Comment by kunjgit** [comment] 2024-01-21 05:54
Hello @U-DAY-333, Time's Uppp!⏰ 
 Sorry for closing your issue! 
 But it's more than a week since we haven't received anything from your side 😢 . 
 Come up with new ideas, create a new issue and make sure you finish it within a week! 🔥 
 All the best! 🚀 
 Happy Hacking! 💗

**Comment by kunjgit** [comment] 2024-01-21 05:54
Hey @U-DAY-333 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Closed by kunjgit** 2024-01-21 05:54 UTC
Labels: gssoc23, New Game 🎮, level3
